### ISSUE TITLE
Tidy Up & Prepare for Public Tweet/Hacker News Post

### ISSUE THREAD

**Issue by nelsonic** [dwyl/tachyons-bootstrap#43]
Most of the _difficult_ work has been done replicating all the Bootstrap Styles! 🎉 
No what need to do is tidy up and _publicise_ it! 

## Todo

+ [x] Create Table-of-Contents so it's easy to find the section and _link_ to it. 
+ [x] Switch to "dwyl" blue (teal) for examples where shading is used e.g: in the Grid System:
Pink is _nice_, but there isn't a _reason_ for us to be using it for this:
![image](https://user-images.githubusercontent.com/194400/26991496-752a68ce-4d52-11e7-9f97-372f2d6c4d5b.png)
Where a darker shade is required use http://www.color-hex.com/color/4db6ac to get the appropriate shade.
![image](https://user-images.githubusercontent.com/194400/26992060-dcfbe836-4d54-11e7-8783-be3df1c83dcf.png)

+ [x] Add word "Tachyons" to all typography to clarify that this is _not_ a "Bootstrap" Heading
![image](https://user-images.githubusercontent.com/194400/26992115-0b8d9c3a-4d55-11e7-9b73-51c90c3d8980.png)

+ [x] Add GitHub "Star Count" Button/Number to top and bottom of the page to encourage others to Star it. e.g: [![GitHub stars](https://img.shields.io/github/stars/badges/shields.svg?style=social&label=Star)](https://github.com/dwyl/start-here) see: https://buttons.github.io

+ [x] Given that the site is `static` does it need to be on Heroku...? https://dwyl-tachyons-bootstrap.herokuapp.com >> Can we use GitHub Pages instead? https://github.com/dwyl/tachyons-bootstrap/issues/15#issuecomment-304431986
+ [x] Create a Subdomain e.g: http://tachyons-bootstrap.dwyl.com pointing to the GitHub Pages Page
+ [x] Add Google Analytics to track how many people view the page and where they came from.
+ [x] Prepare intro video: https://github.com/dwyl/tachyons-bootstrap/issues/9
+ [ ] Pick a good picture to use for the Tweet. [`help wanted`]
+ [ ] Make YouTube videos public
+ [ ] Add a comment on this blog: https://medium.com/@dakotaleemartinez/keeping-your-css-dry-with-tachyons-bb1c0dc66dce about tachyons bootstrap as it directly compares the two

**Comment by Cleop** [comment]
@nelsonic - I've updated #9 with questions to answer in order to get that issue under way.

**Comment by Cleop** [comment]
I've given this an epic label because some of the issues are hard to time estimate and may be large, e.g. the video introduction as they've not been fully defined yet. I'll separate the issue out into individual issues.

@iteles is going to: Create a Subdomain e.g: http://tachyons-bootstrap.dwyl.com pointing to the GitHub Pages Page once I've provided her with what she needs for this.

@iteles recommended the resource: https://help.github.com/articles/setting-up-an-apex-domain/#configuring-a-records-with-your-dns-provider where I have completed step 1 by saving http://tachyons-bootstrap.dwyl.com in the custom domain option.

**Comment by ghost** [comment]
Also publicise here: http://tachyons-slack-invite.herokuapp.com/
<img width="313" alt="screen shot 2017-06-22 at 16 11 22" src="https://user-images.githubusercontent.com/5732209/27441454-877335a2-5765-11e7-8a75-7686f476721b.png">

I'm in 👍 🕵️ 

@cleop readme also needs updating
