### ISSUE TITLE
COLORS: Create colors.html and include in index.html

### ISSUE THREAD

**Issue by nelsonic** [dwyl/tachyons-bootstrap#72]
As a person who is `new` to building UI with Tachyons, 
I want to know what built-in colors are available
So that I can easily select the [font|background] color I need.

https://tachyons.io/docs/themes/skins/
![image](https://user-images.githubusercontent.com/194400/152254443-acc2258a-c4cf-4a62-9221-241cc3e75cc7.png)

# Todo

+ [ ] Create `colors.html` in [`/components`](https://github.com/dwyl/tachyons-bootstrap/tree/master/components)
+ [ ] Borrow the code directly from the https://tachyons.io/docs/themes/skins/ page 
+ [ ] Include the `colors.html` below Typography:
https://github.com/dwyl/tachyons-bootstrap/blob/d57d83e4ad072f51dc65f4328707ebb8d117c011/index.html#L52

**Comment by nelsonic** [comment]
Fairly easy to lift-and-shift the color list and add a usage section:
![image](https://user-images.githubusercontent.com/194400/152330966-028f0a1b-019b-47dd-83ad-c7adf3d06a05.png)

PR: #73

**Comment by nelsonic** [comment]
Deployed: https://tachyons-bootstrap.dwyl.com/#colors 🌈 
![image](https://user-images.githubusercontent.com/194400/152774057-57c9f3b2-8da3-475f-943c-e18bf0b5c3ad.png)

Thanks to @SimonLab for reviewing/merging. 👍
